name: Build

on:
  push:
    branches:                                                                   
    - '*'                                                                       

env:
  CARGO_TERM_COLOR: always

jobs:
  toolchains:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [ nightly, beta, stable, 1.47.0 ]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libzmq3-dev libpcre3-dev libpq-dev libssl-dev
      - name: Install rust ${{matrix.toolchain}}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.toolchain}}
          override: true
      - name: All features
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace --all-targets --all-features
